package com.mindblown.backupper;



import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

/**
 *
 * @author beamj
 */
public class DrivePanel extends javax.swing.JPanel {
    
    private Drive drive;
    private Register register;
    private JDialog editPanelDial;
    public static DrivePanel drivePan;
    
    /**
     * Creates new form DrivePanel
     * @param drive
     * @param register
     */
    public DrivePanel(Drive drive, Register register) {
        this.drive = drive;
        this.register = register;
        initComponents();
        drivePan = this;
    }
    
    private String getButtonText(){
        boolean hasRegistry = Register.hasRegistry(drive);
        if(hasRegistry){
            if(isRegistered()){
                return "Edit Registration";
            } else {
                return "Add Registry";
            }
        } else {
            return "Register";
        }
    }
    
    private String getLabelText(){
        if(isRegistered()){
            return "Registered";
        } else {
            return "UnRegistered";
        }
    }
    
    private boolean isRegistered(){
        return register.registered(drive);
    }
    
    private void setFields(){
        regLabel.setText(getLabelText());
        regButton.setText(getButtonText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regLabel = new javax.swing.JLabel();
        regButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), drive.getRoot(), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        regLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regLabel.setText(getLabelText());
        regLabel.setToolTipText("");
        jPanel1.add(regLabel);

        regButton.setText(getButtonText());
        regButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regButtonMouseClicked(evt);
            }
        });
        jPanel1.add(regButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void regButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regButtonMouseClicked
        if(!Register.hasRegistry(drive)){
            register.register(drive);
        } else {
            if(isRegistered()){
                RegistryEditPanel pan = new RegistryEditPanel(register.getRegistry(drive));
                JOptionPane pane = new JOptionPane(pan, JOptionPane.PLAIN_MESSAGE);
                editPanelDial = pane.createDialog(this, "Edit " + drive.getRoot() + "'s Registry");
                editPanelDial.setVisible(true);
            } else {
                register.addRegistry(drive);
            }
        }
        setFields();
    }//GEN-LAST:event_regButtonMouseClicked
    
    public void disposeEdit(){
        register.deregister(drive);
        editPanelDial.dispose();
        Main.main.cacheRegister();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regButton;
    private javax.swing.JLabel regLabel;
    // End of variables declaration//GEN-END:variables
}
