package com.mindblown.backupper;


import com.mindblown.backupper.FileSetCreator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author beamj
 */
public class FileSetEditor extends javax.swing.JPanel {

    private FileAction fa;
    
    /**
     * Creates new form FileSetEdiitor
     * @param fa
     */
    public FileSetEditor(FileAction fa) {
        initComponents();
        this.fa = fa;
    }
    
    public FileAction getFileAction(){
        if(fa == null){
            return null;
        }
        if(!fa.isReal()){
            return null;
        }
        return fa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editButton = new javax.swing.JButton();
        backupButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(3, 0));

        editButton.setText("Edit File Set");
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });
        add(editButton);

        backupButton.setText("Backup");
        backupButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backupButtonMouseClicked(evt);
            }
        });
        add(backupButton);

        deleteButton.setText("Delete File Set");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        add(deleteButton);
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        FileSetCreator pan = new FileSetCreator(fa);
        Util.message(this, pan, "Edit File Set");
        fa = pan.getFileAction();
    }//GEN-LAST:event_editButtonMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        fa = null;
        RegistryEditPanel.staticPan.disposeTimeDial();
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void backupButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupButtonMouseClicked
        if(fa.isReal()){
            Backupper.backup(fa.getFile1(), fa.getFile2());
        }
    }//GEN-LAST:event_backupButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backupButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    // End of variables declaration//GEN-END:variables
}
