package com.mindblown.backupper;


import com.mindblown.backupper.FileSetCreator;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/

/**
 *
 * @author beamj
 */
public class RegistryEditPanel extends javax.swing.JPanel {
    
    private Registry registry;
    private RegistryFilesTableModel model;
    private JDialog timeSetDial;
    public static RegistryEditPanel staticPan;
    
    /**
     * Creates new form RegistryEditPanel
     * @param registry
     */
    public RegistryEditPanel(Registry registry) {
        this.registry = registry;
        model = new RegistryFilesTableModel(registry);
        initComponents();
        staticPan = this;
    }
    
    private void updateModel(){
        Main.main.cacheRegister();
        filesTable.revalidate();
        repaint();
    }
    
    public void disposeTimeDial(){
        timeSetDial.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filesTable = new javax.swing.JTable();
        addFileSetButton = new javax.swing.JButton();
        backupAllButton = new javax.swing.JButton();

        deleteButton.setText("Delete Registration");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Edit Backup Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        filesTable.setModel(model);
        filesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(filesTable);

        addFileSetButton.setText("Add File Set");
        addFileSetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFileSetButtonMouseClicked(evt);
            }
        });

        backupAllButton.setText("Backup All");
        backupAllButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backupAllButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(backupAllButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(addFileSetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addFileSetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backupAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        DrivePanel.drivePan.disposeEdit();
    }//GEN-LAST:event_deleteButtonMouseClicked
    
    private void filesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filesTableMouseClicked
        if(evt.getClickCount() != 2){
            return;
        }
        FileAction fa = registry.getFileActions().get(filesTable.getSelectedRow());
        FileSetEditor pan = new FileSetEditor(fa);
        JOptionPane pane = new JOptionPane(pan);
        timeSetDial = pane.createDialog(this, "Edit File Set");
        timeSetDial.setVisible(true);
        FileAction fa1 = pan.getFileAction();
        if(fa1 != null && !fa1.equals(fa)){
            fa = fa1;
            registry.addFileAction(fa);
            updateModel();
        } else if(fa1 == null){
            model.removeFileAction(fa);
            updateModel();
        }
    }//GEN-LAST:event_filesTableMouseClicked
    
    private void addFileSetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFileSetButtonMouseClicked
        FileSetCreator pan = new FileSetCreator(new FileAction(null, null));
        Util.message(this, pan, "Add New File Set");
        FileAction fa = pan.getFileAction();
        if(fa.getFile1() != null && fa.getFile2() != null){
            registry.addFileAction(fa);
            Main.main.cacheRegister();
            filesTable.revalidate();
            repaint();
        }
    }//GEN-LAST:event_addFileSetButtonMouseClicked

    private void backupAllButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupAllButtonMouseClicked
        registry.backupAll();
    }//GEN-LAST:event_backupAllButtonMouseClicked
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFileSetButton;
    private javax.swing.JButton backupAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable filesTable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}